Repository treasure-data/digdag, pull requests merged in 2019-06, with the labels that each got.

#1148 Add detailed usage of py> operator
  digdag-docs/src/operators/py.md
Labels: document

#1141 Fix error when schema_update_options given
  digdag-standards/src/main/java/io/digdag/standards/operator/gcp/BqLoadOperatorFactory.java
Labels: bug

#1143 Introduce py> operator error message and stacktrace on error
  digdag-standards/src/main/java/io/digdag/standards/operator/PyOperatorFactory.java
  digdag-standards/src/main/resources/digdag/standards/py/runner.py
  digdag-tests/src/test/java/acceptance/PyIT.java
  digdag-tests/src/test/resources/acceptance/py/scripts/__init__.py
  digdag-tests/src/test/resources/acceptance/py/scripts/stacktrace.py
  digdag-tests/src/test/resources/acceptance/py/stacktrace_python.dig
Labels: enhancement

#1154 Bump up Sphinx 2.1.1
  .circleci/config.yml
  .gitignore
  README.md
  digdag-docs/Makefile
  digdag-docs/constraints.txt
  digdag-docs/make.bat
  digdag-docs/requirements.txt
  digdag-docs/src/conf.py
  digdag-docs/src/scheduling_workflow.rst
  digdag-docs/src/workflow_definition.rst
  docker/Makefile
  docker/bootstrap/dependencies.sh
Labels: document, enhancement

#1162 Stop using imp module
  .gitignore
  digdag-standards/src/main/resources/digdag/standards/py/runner.py
Labels: enhancement
