Repository treasure-data/digdag, pull requests merged in 2019-03, with the labels that each got.

#1022 rb>: operator supports ruby option arguments
  digdag-docs/src/operators/rb.md
  digdag-standards/src/main/java/io/digdag/standards/operator/RbOperatorFactory.java
  digdag-tests/src/test/java/acceptance/RbIT.java
  digdag-tests/src/test/resources/acceptance/echo_params/echo_rb_params.dig
  digdag-tests/src/test/resources/acceptance/echo_params/scripts/echo_params.rb
  digdag-tests/src/test/resources/acceptance/rb/config_ruby.dig
Labels: feature_request

#1020 digdag reschedule <project-name> <name>
  digdag-cli/src/main/java/io/digdag/cli/Main.java
  digdag-cli/src/main/java/io/digdag/cli/client/DisableSchedule.java
  digdag-cli/src/main/java/io/digdag/cli/client/EnableSchedule.java
  digdag-cli/src/main/java/io/digdag/cli/client/Reschedule.java
  digdag-docs/src/command_reference.rst
  digdag-tests/src/test/java/acceptance/RescheduleIT.java
  digdag-tests/src/test/resources/acceptance/reschedule/reschedule.dig
Labels: enhancement

#1023 py>: operator supports python option arguments
  digdag-docs/src/operators/py.md
  digdag-standards/src/main/java/io/digdag/standards/operator/PyOperatorFactory.java
  digdag-tests/src/test/java/acceptance/PyIT.java
  digdag-tests/src/test/resources/acceptance/py/config_python.dig
Labels: feature_request

#1026 Digdag push validation on the server side.
  digdag-server/src/main/java/io/digdag/server/rs/ProjectResource.java
  digdag-tests/src/test/java/acceptance/ValidateProjectIT.java
  digdag-tests/src/test/resources/acceptance/schedule/invalid_schedule.dig
Labels: bug, feature_request

#1054 Fix ParamServer DEFAULT_TTL value.
  digdag-spi/src/main/java/io/digdag/spi/ParamServerClient.java
  digdag-standards/src/main/java/io/digdag/standards/operator/param/PostgresqlParamServerClient.java
  digdag-standards/src/main/java/io/digdag/standards/operator/param/RedisParamServerClient.java
  digdag-tests/src/test/java/acceptance/ParamGetPostgresqlIT.java
  digdag-tests/src/test/java/acceptance/ParamSetRedisIT.java
Labels: bug

#1063 Use 'npm ci' instead of 'npm install' to avoid update of package-lock…
  build.gradle
Labels: enhancement
