Repository treasure-data/digdag, pull requests merged in 2019-12, with the labels that each got.

#1269 Fix typo, wrong database name.
  digdag-core/src/main/java/io/digdag/core/database/DatabaseConfig.java
Labels: bug

#1240 Implement td_result_export> operator with specifying a result_connection version
  digdag-docs/src/operators/td_result_export.md
  digdag-standards/src/main/java/io/digdag/standards/operator/OperatorModule.java
  digdag-standards/src/main/java/io/digdag/standards/operator/td/BaseTdJobOperator.java
  digdag-standards/src/main/java/io/digdag/standards/operator/td/TDOperator.java
  digdag-standards/src/main/java/io/digdag/standards/operator/td/TDResultExportOperatorFactory.java
  digdag-tests/src/test/java/acceptance/td/TdResultExportIT.java
  digdag-tests/src/test/resources/acceptance/td/td_result_export/td_result_export.dig
Labels: feature_request

#1270 Remove task request sending from digdag-metrics.
  digdag-core/src/main/java/io/digdag/core/agent/OperatorManager.java
  digdag-server/src/main/java/io/digdag/server/metrics/DigdagMetricsModule.java
  digdag-server/src/main/java/io/digdag/server/metrics/jmx/DigdagJmxMeterRegistry.java
Labels: bug

#1273 [Doc] Add _check and _error example
  digdag-docs/src/concepts.md
Labels: document

#1277 [doc] Add log-server.local.split_size description.
  digdag-docs/src/command_reference.rst
Labels: document

#1263 Support GCS
  digdag-cli/build.gradle
  digdag-docs/src/command_reference.rst
  digdag-standards/build.gradle
  digdag-standards/src/main/java/io/digdag/standards/operator/HttpOperatorFactory.java
  digdag-standards/src/main/java/io/digdag/standards/operator/aws/EmrOperatorFactory.java
  digdag-storage-gcs/build.gradle
  digdag-storage-gcs/src/main/java/io/digdag/storage/gcs/GCSStorage.java
  digdag-storage-gcs/src/main/java/io/digdag/storage/gcs/GCSStorageExtension.java
  digdag-storage-gcs/src/main/java/io/digdag/storage/gcs/GCSStorageFactory.java
  digdag-storage-gcs/src/main/resources/META-INF/services/io.digdag.spi.Extension
  digdag-storage-gcs/src/test/java/io/digdag/storage/gcs/GCSStorageTest.java
  digdag-tests/build.gradle
  digdag-tests/src/test/java/acceptance/HttpIT.java
  digdag-tests/src/test/java/acceptance/td/EmrIT.java
  digdag-tests/src/test/java/acceptance/td/GcpUtil.java
  settings.gradle
Labels: enhancement

#1280 Introduce timeout to s3_wait> operator.
  digdag-docs/src/operators/s3_wait.md
  digdag-standards/src/main/java/io/digdag/standards/operator/aws/S3WaitOperatorFactory.java
  digdag-standards/src/main/java/io/digdag/standards/operator/gcp/GcsWaitOperatorFactory.java
  digdag-standards/src/main/java/io/digdag/standards/operator/state/PollingTimeoutException.java
  digdag-standards/src/main/java/io/digdag/standards/operator/state/PollingWaiter.java
  digdag-standards/src/test/java/io/digdag/standards/operator/aws/S3WaitOperatorFactoryTest.java
  digdag-standards/src/test/java/io/digdag/standards/operator/state/PollingWaiterTest.java
  digdag-tests/src/test/java/acceptance/S3WaitIT.java
  digdag-tests/src/test/resources/acceptance/s3/s3_wait_continue_on_timeout.dig
  digdag-tests/src/test/resources/acceptance/s3/s3_wait_timeout.dig
Labels: enhancement

#1287 Add swagger documents
  .gitignore
  README.md
  build.gradle
  digdag-docs/src/_static/swagger.yaml
  digdag-docs/src/index.md
  digdag-docs/src/rest_api.rst
  digdag-server/src/main/java/io/digdag/server/rs/AttemptResource.java
  digdag-server/src/main/java/io/digdag/server/rs/LogResource.java
  digdag-server/src/main/java/io/digdag/server/rs/ProjectResource.java
  digdag-server/src/main/java/io/digdag/server/rs/ScheduleResource.java
  digdag-server/src/main/java/io/digdag/server/rs/SessionResource.java
  digdag-server/src/main/java/io/digdag/server/rs/VersionResource.java
  digdag-server/src/main/java/io/digdag/server/rs/WorkflowResource.java
Labels: document, enhancement

#1286 Add @Deprecated annotation to deprecated JAX-RS resources for Swagger
  digdag-cli/src/main/java/io/digdag/cli/Server.java
  digdag-server/src/main/java/io/digdag/server/rs/AdminResource.java
  digdag-server/src/main/java/io/digdag/server/rs/ProjectResource.java
  digdag-server/src/main/java/io/digdag/server/rs/WorkflowResource.java
Labels: enhancement

#1288 Filter project revisions API by name
  digdag-server/src/main/java/io/digdag/server/rs/ProjectResource.java
Labels: enhancement
