Repository treasure-data/digdag, pull requests merged in 2019-05, with the labels that each got.

#1094 Document the availability of packages on various platforms (follow up of #1089)
  digdag-docs/src/getting_started.md
Labels: document

#1105 [doc] secret key generation example
  digdag-docs/src/command_reference.rst
Labels: document

#1102 [Doc] Var defined in _export is not overwritable by --param
  digdag-docs/src/command_reference.rst
Labels: document

#1118 Update the condition for filterSessionsByStatus
  digdag-ui/console.jsx
Labels: bug

#1104 Add max_interval to exponential retrying option
  digdag-core/src/test/java/io/digdag/core/workflow/WorkflowExecutorTest.java
  digdag-core/src/test/resources/io/digdag/core/workflow/retry_exponential.dig
  digdag-plugin-utils/src/main/java/io/digdag/util/RetryControl.java
Labels: enhancement

#1082 Adding http_call operator
  digdag-docs/src/operators/http_call.md
  digdag-docs/src/operators/workflow_control.rst
  digdag-standards/src/main/java/io/digdag/standards/operator/HttpCallOperatorFactory.java
  digdag-standards/src/main/java/io/digdag/standards/operator/HttpOperatorFactory.java
  digdag-standards/src/main/java/io/digdag/standards/operator/OperatorModule.java
  digdag-tests/src/test/java/acceptance/HttpCallIT.java
  digdag-tests/src/test/resources/acceptance/http_call/child.dig
  digdag-tests/src/test/resources/acceptance/http_call/http_call.dig
  digdag-tests/src/test/resources/acceptance/http_call/http_call_post.dig
  digdag-tests/src/test/resources/acceptance/http_call/http_call_query.dig
Labels: feature_request

#1024 rb>: operator shows ruby error message and stacktrace on error (next. waiting to be merged)
  digdag-standards/src/main/java/io/digdag/standards/operator/RbOperatorFactory.java
  digdag-standards/src/main/resources/digdag/standards/rb/runner.rb
  digdag-tests/src/test/java/acceptance/RbIT.java
  digdag-tests/src/test/resources/acceptance/rb/scripts/stacktrace_ruby.rb
  digdag-tests/src/test/resources/acceptance/rb/stacktrace_ruby.dig
Labels: feature_request

#1025 _export: docker: supports docker option arguments
  ci/run_test_docker.sh
  digdag-standards/src/main/java/io/digdag/standards/command/DockerCommandExecutor.java
  digdag-tests/src/test/java/acceptance/DockerIT.java
  digdag-tests/src/test/resources/acceptance/docker/docker_build.dig
  digdag-tests/src/test/resources/acceptance/docker/docker_run_options.dig
Labels: feature_request

#1095 Add job_retry parameter to td query operators
  digdag-docs/src/operators/td.md
  digdag-docs/src/operators/td_for_each.md
  digdag-docs/src/operators/td_wait.md
  digdag-docs/src/operators/td_wait_table.md
Labels: document
