Repository treasure-data/digdag, pull requests merged in 2019-07, with the labels that each got.

#1159 Fix some doc typos, explain group retry/vs task retry more
  digdag-docs/src/workflow_definition.rst
Labels: document

#1165 Fix the message of invalid ISO time format error
  digdag-client/src/main/java/io/digdag/client/api/JacksonTimeModule.java
Labels: bug

#1164 Modify wrong sample
  digdag-docs/src/operators/td_run.md
Labels: document

#1130 Update release procedure
  README.md
Labels: document

#1098 Issue #1079: Moved the Authenticator interface to the SPI module.
  digdag-cli/src/main/java/io/digdag/cli/Server.java
  digdag-docs/src/command_reference.rst
  digdag-docs/src/internal.md
  digdag-server/src/main/java/io/digdag/server/AuthRequestFilter.java
  digdag-server/src/main/java/io/digdag/server/ServerBootstrap.java
  digdag-server/src/main/java/io/digdag/server/ServerConfig.java
  digdag-server/src/main/java/io/digdag/server/ServerModule.java
  digdag-server/src/test/java/io/digdag/server/AuthRequestFilterTest.java
  digdag-server/src/test/java/io/digdag/server/AuthenticatorTest.java
  digdag-spi/src/main/java/io/digdag/spi/Authenticator.java
  digdag-standards/src/main/java/io/digdag/standards/auth/jwt/JwtAuthenticator.java
  digdag-standards/src/main/java/io/digdag/standards/auth/jwt/JwtAuthenticatorConfig.java
  digdag-standards/src/main/java/io/digdag/standards/auth/jwt/JwtAuthenticatorConfigProvider.java
  digdag-standards/src/main/java/io/digdag/standards/auth/jwt/JwtAuthenticatorPlugin.java
  digdag-standards/src/main/java/io/digdag/standards/auth/jwt/UserConfig.java
  digdag-standards/src/main/resources/META-INF/services/io.digdag.spi.Plugin
Labels: feature_request

#1144 Add project_id parameter to require operator doc
  digdag-docs/src/operators/require.md
Labels: document

#1181 [doc] Add params option description in require> operator.
  digdag-docs/src/operators/require.md
Labels: document

#1192 Add workflow definition ID to notification
  digdag-core/src/main/java/io/digdag/core/notification/MailNotificationSender.java
  digdag-core/src/main/java/io/digdag/core/workflow/WorkflowExecutor.java
  digdag-server/src/main/java/io/digdag/server/WorkflowExecutionTimeoutEnforcer.java
  digdag-spi/src/main/java/io/digdag/spi/Notification.java
  digdag-spi/src/main/java/io/digdag/spi/TaskRequest.java
  digdag-standards/src/main/java/io/digdag/standards/operator/NotifyOperatorFactory.java
Labels: enhancement
