Repository treasure-data/digdag, pull requests merged in 2019-04, with the labels that each got.

#1070 Add client options in usage
  digdag-cli/src/main/java/io/digdag/cli/Main.java
Labels: enhancement

#1068 UI: Show attempt params to attempt/session views
  digdag-ui/console.jsx
  digdag-ui/style.less
Labels: enhancement

#1072 HikariCP JMX metrics
  digdag-core/src/main/java/io/digdag/core/database/DataSourceProvider.java
  digdag-core/src/main/java/io/digdag/core/database/DatabaseConfig.java
  digdag-core/src/test/java/io/digdag/core/database/DatabaseTestingUtils.java
  digdag-docs/src/command_reference.rst
  digdag-tests/src/test/java/acceptance/ServerJmxIT.java
Labels: enhancement

#1067 [Doc] Update release procedure.
  README.md
Labels: document

#1064 [Doc] Add variables to variable table for schedule.
  digdag-docs/src/workflow_definition.rst
Labels: document

#1073 Fix the issue which causes infinite task retry.
  digdag-core/src/main/java/io/digdag/core/agent/OperatorManager.java
  digdag-tests/src/test/java/acceptance/ConfigEvalEngineIT.java
  digdag-tests/src/test/resources/acceptance/config_eval_engine/invalid1.dig
Labels: bug

#1060 Introduce `digdag projects` cmd
  digdag-cli/src/main/java/io/digdag/cli/Main.java
  digdag-cli/src/main/java/io/digdag/cli/client/ShowProjects.java
  digdag-tests/src/test/java/acceptance/CliShowProjectsIT.java
Labels: enhancement

#1081 Add npm packages to fix missing peer dependencies
  digdag-ui/package-lock.json
  digdag-ui/package.json
Labels: bug

#1061 Feature add index to session attempts
  digdag-cli/src/main/java/io/digdag/cli/Main.java
  digdag-cli/src/main/java/io/digdag/cli/Migrate.java
  digdag-core/src/main/java/io/digdag/core/database/DatabaseMigrator.java
  digdag-core/src/main/java/io/digdag/core/database/DatabaseModule.java
  digdag-core/src/main/java/io/digdag/core/database/migrate/Migration.java
  digdag-core/src/main/java/io/digdag/core/database/migrate/Migration_20190318175338_AddIndexToSessionAttempts.java
  digdag-core/src/test/java/io/digdag/core/database/DatabaseTestingUtils.java
  digdag-docs/src/command_reference.rst
  digdag-docs/src/db_migration.md
  digdag-tests/src/test/java/acceptance/CliMigrateIT.java
  digdag-tests/src/test/java/acceptance/MigrationIT.java
  digdag-tests/src/test/java/utils/TemporaryDigdagServer.java
Labels: enhancement
