Repository treasure-data/digdag, pull requests merged in 2019-02, with the labels that each got.

#965 Fix that DigdagClient raises JsonParseException
  digdag-client/src/main/java/io/digdag/client/DigdagClient.java
  digdag-client/src/test/java/io/digdag/client/DigdagClientTest.java
Labels: bug

#1007 Fix typo
  digdag-docs/src/operators/http.md
Labels: document

#1006 [doc] Add version command
  digdag-docs/src/command_reference.rst
Labels: document

#1001 [doc] Modify wrong argument of attempts command
  digdag-docs/src/command_reference.rst
Labels: document

#1002 [doc] Add attempt command to the document
  digdag-docs/src/command_reference.rst
Labels: document

#1008 [doc] Add disable/enable command
  digdag-docs/src/command_reference.rst
Labels: document

#1005 [doc] add doc about force option for delete command
  digdag-docs/src/command_reference.rst
Labels: document

#1004 [doc] Add session command to the document
  digdag-docs/src/command_reference.rst
Labels: document

#1021 Support digdag backfill <schedule-id>
  digdag-cli/src/main/java/io/digdag/cli/client/Backfill.java
  digdag-docs/src/command_reference.rst
  digdag-tests/src/test/java/acceptance/BackfillIT.java
Labels: enhancement

#1019 [doc] Add doc about scheduler syntax
  digdag-docs/src/scheduling_workflow.rst
Labels: document

#1029 [doc] Add http operator timeout description
  digdag-docs/src/operators/http.md
Labels: document
