Repository treasure-data/digdag, pull requests merged in 2019-09, with the labels that each got.

#1218 added description choosing another DB which is not specified with _ex…
  digdag-docs/src/operators/td_ddl.md
Labels: document

#1187 Fix n-m db access in ProjectResource.getProjects to add projectsWithLatestRevision
  digdag-core/src/main/java/io/digdag/core/database/DatabaseProjectStoreManager.java
  digdag-core/src/main/java/io/digdag/core/database/ThreadLocalTransactionManager.java
  digdag-core/src/main/java/io/digdag/core/repository/ProjectStore.java
  digdag-core/src/main/java/io/digdag/core/repository/StoredProjectWithRevision.java
  digdag-core/src/test/java/io/digdag/core/database/DatabaseProjectStoreManagerTest.java
  digdag-server/src/main/java/io/digdag/server/rs/ProjectResource.java
  digdag-server/src/main/java/io/digdag/server/rs/RestModels.java
Labels: enhancement

#1221 Add echo log output to task log.
  digdag-standards/src/main/java/io/digdag/standards/operator/EchoOperatorFactory.java
Labels: enhancement

#1225 Fix bq output parameter.
  digdag-docs/src/operators/bq.md
  digdag-docs/src/operators/bq_extract.md
  digdag-docs/src/operators/bq_load.md
  digdag-standards/src/main/java/io/digdag/standards/operator/gcp/BaseBqJobOperator.java
Labels: bug
