Repository treasure-data/digdag, pull requests merged in 2020-06, with the labels that each got.

#1398 Add attempt status response
  .gitignore
  digdag-cli/src/main/java/io/digdag/cli/client/ShowAttempt.java
  digdag-cli/src/main/java/io/digdag/cli/client/ShowAttempts.java
  digdag-client/src/main/java/io/digdag/client/api/RestSessionAttempt.java
  digdag-client/src/test/java/io/digdag/client/api/ModelCompatibilityTest.java
  digdag-docs/src/_extra/api/swagger.yaml
Labels: enhancement

#1409 require> enhancement
  digdag-client/src/main/java/io/digdag/client/DigdagClient.java
  digdag-core/src/main/java/io/digdag/core/agent/InProcessTaskCallbackApi.java
  digdag-core/src/main/java/io/digdag/core/agent/RequireOperatorFactory.java
  digdag-core/src/main/java/io/digdag/core/agent/TaskCallbackApi.java
  digdag-docs/src/operators/require.md
  digdag-tests/src/test/java/acceptance/RequireIT.java
  digdag-tests/src/test/resources/acceptance/require/child_another_project.dig
  digdag-tests/src/test/resources/acceptance/require/child_rerun_on.dig
  digdag-tests/src/test/resources/acceptance/require/parent_another_project.dig
  digdag-tests/src/test/resources/acceptance/require/parent_rerun_on.dig
Labels: enhancement

#1422 [backport] require> enhancement
  digdag-client/src/main/java/io/digdag/client/DigdagClient.java
  digdag-core/src/main/java/io/digdag/core/agent/InProcessTaskCallbackApi.java
  digdag-core/src/main/java/io/digdag/core/agent/RequireOperatorFactory.java
  digdag-core/src/main/java/io/digdag/core/agent/TaskCallbackApi.java
  digdag-docs/src/operators/require.md
  digdag-tests/src/test/java/acceptance/RequireIT.java
  digdag-tests/src/test/resources/acceptance/require/child_another_project.dig
  digdag-tests/src/test/resources/acceptance/require/child_rerun_on.dig
  digdag-tests/src/test/resources/acceptance/require/parent_another_project.dig
  digdag-tests/src/test/resources/acceptance/require/parent_rerun_on.dig
Labels: enhancement

#1420 [doc] add embulk option to docs
  digdag-docs/src/operators/embulk.md
Labels: document

#1353 Fix Uncaught TypeError: e.charAt is not a function
  digdag-ui/console.jsx
Labels: bug

#1379 UI: Disable automatic updating for AttemptLogsView
  digdag-ui/console.jsx
Labels: enhancement

#1199 Add option to copy symbolic links pointing outside of project directory
  digdag-cli/src/main/java/io/digdag/cli/client/Archive.java
  digdag-cli/src/main/java/io/digdag/cli/client/Archiver.java
  digdag-cli/src/main/java/io/digdag/cli/client/Push.java
  digdag-core/src/main/java/io/digdag/core/archive/ProjectArchive.java
  digdag-core/src/main/java/io/digdag/core/archive/ProjectArchiveLoader.java
  digdag-core/src/test/java/io/digdag/core/archive/ProjectArchiveTest.java
  digdag-docs/src/command_reference.rst
  digdag-tests/src/test/java/acceptance/CliArchiveIT.java
Labels: enhancement
